project_name: ExerciseDiary
builds:
  - id: api
    main: ./cmd/api/
    binary: exercisediary-api
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

  - id: frontend
    main: ./cmd/frontend/
    binary: exercisediary-frontend
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

nfpms:
  - maintainer: aceberg <aceberg_a@proton.me>
    description: Workout diary with GitHub-style year visualization
    homepage: https://github.com/aceberg/ExerciseDiary
    license: MIT
    section: utils
    formats:
    - deb
    - rpm
    - apk
    - termux.deb
    contents:
    - src: ./configs/exercisediary-api.service
      dst: /lib/systemd/system/exercisediary-api.service
    - src: ./configs/exercisediary-frontend.service
      dst: /lib/systemd/system/exercisediary-frontend.service
    scripts:
      postinstall: ./configs/postinstall.sh

archives:
  - files:
    - LICENSE
    - README.md
    - CHANGELOG.md
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: "checksums.txt"
