FROM golang:alpine AS builder

COPY . /src
RUN cd /src && CGO_ENABLED=0 go build -o /workoutdiary-frontend ./cmd/frontend

FROM scratch

WORKDIR /data/WorkoutDiary
WORKDIR /app

COPY --from=builder /workoutdiary-frontend /app/

ENTRYPOINT ["./workoutdiary-frontend"]
