FROM golang:alpine AS builder

RUN apk add --no-cache build-base
COPY . /src
RUN cd /src && CGO_ENABLED=0 go build -o /workoutdiary-api ./cmd/api

FROM scratch

WORKDIR /data/WorkoutDiary
WORKDIR /app

COPY --from=builder /workoutdiary-api /app/

ENTRYPOINT ["./workoutdiary-api"]
