version: "3"
services:
  exdiary-api:
    image: ghcr.io/rwlove/exercisediary-api:latest
    restart: unless-stopped
    ports:
    - 8851:8851
    volumes:
    - ~/.dockerdata/ExerciseDiary:/data/ExerciseDiary
    environment:
      TZ: America/New_York    # required, default: ""

  exdiary-frontend:
    image: ghcr.io/rwlove/exercisediary-frontend:latest
    restart: unless-stopped
    ports:
    - 8080:8080
    command: "-a http://exdiary-api:8851"
    depends_on:
      - exdiary-api
    environment:
      TZ: America/New_York    # required, default: ""
